variables:
- group: Extensions Patch Versions
- name: version.MajorMinor # Manually adjust the version number as needed for semantic versioning. Patch is auto-incremented.
  value: '1.1'
- name: extensionName
  value: 'kanban-board-tools'
- name: marketplaceServiceConnection
  value: 'marketplaceServiceConnection'
- name: publisherId
  value: 'alm-devops-rangers'
- name: publicExtensionName
  value: "Azure Boards Kanban Tools"
- name: version.Patch
  value: $[counter(variables['version.MajorMinor'],variables['kanbanToolPatchVer'])]
- name: versionNumber
  value: '$(version.MajorMinor).$(version.Patch)'

name: $(version.MajorMinor)$(rev:.r)

trigger:
  branches:
    include:
    - main

pr: none

resources:
  repositories:
    - repository: pipeline-templates
      type: git
      name: Sage/pipeline-templates
      ref: main

stages:
- stage: 'Build'
  jobs:
  - job: 'BuildPack'
    displayName: "Build and package"
    pool:
      vmImage: ubuntu-latest
    steps:


    - task: PowerShell@2
      displayName: Set the name of the build (i.e. the Build.BuildNumber)
      inputs:
        targetType: 'inline'
        script: |
          [string] $buildName = "$(versionNumber)"
          Write-Host "Setting the name of the build to '$buildName'."
          Write-Host "##vso[build.updatebuildnumber]$buildName"

    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
    - template: build.yml@pipeline-templates
    - template: package.yml@pipeline-templates
      parameters:
        extensionName: $(extensionName)
        outputPath: 'out'
        rootPath: './dist'

- stage: 'DeployDev'
  displayName: 'Deploy to dev'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - template: deploy.yml@pipeline-templates
    parameters:
      environment: 'dev'
      extensionName: $(extensionName)
      marketplaceConnectedServiceName: $(marketplaceServiceConnection)
      publisherId: $(publisherId)
      publicExtensionName: $(publicExtensionName)

- stage: 'DeployTest'
  displayName: 'Deploy to Test'
  dependsOn: DeployDev
  condition: succeeded()
  jobs:
  - template: deploy.yml@pipeline-templates
    parameters:
      environment: 'test'
      extensionName: $(extensionName)
      marketplaceConnectedServiceName: $(marketplaceServiceConnection)
      publisherId: $(publisherId)
      publicExtensionName: $(publicExtensionName)

- stage: 'DeployRelease'
  displayName: 'Deploy Release'
  dependsOn: DeployTest
  condition: succeeded()
  jobs:
  - template: deploy.yml@pipeline-templates
    parameters:
      environment: 'public'
      extensionName: $(extensionName)
      marketplaceConnectedServiceName: $(marketplaceServiceConnection)
      publisherId: $(publisherId)
      publicExtensionName: $(publicExtensionName)
      extensionVisibility: 'public'